vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        actualite_fichier:
            uri_prefix: /uploads/actualite
            upload_destination: '%kernel.project_dir%/public/uploads/actualite'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
